name: 'Get and cache requirements'
description: 'Cache and install Python dependencies'
runs:
  using: 'composite'
  steps:
    - name: Cache virtual environment
      id: cache-venv
      uses: actions/cache@v4
      with:
        path: .venv
        key: ${{ runner.os }}-venv-${{ hashFiles('requirements.txt', 'test/test.requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-venv-

    - name: Create virtual environment
      if: steps.cache-venv.outputs.cache-hit != 'true'
      run: python -m venv .venv
      shell: bash

    - name: Install dependencies
      if: steps.cache-venv.outputs.cache-hit != 'true'
      run: |
        source .venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r test/test.requirements.txt
      shell: bash