name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: test
          MYSQL_PASSWORD: test
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u test -ptest"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
          --default-authentication-plugin=mysql_native_password

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest mysql-connector-python

      - name: Run tests
        run: |
          source .venv/bin/activate
          PYTHONPATH=src python -m pytest test/test_mysql_honeypot_unit.py -v --log-level=INFO
        env:
          MYSQL_TEST_PASSWORD: test