name: Run Tests
on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Create virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip

      - name: Install dependencies
        run: |
          source .venv/bin/activate
          pip install -r requirements.txt
          pip install pytest

      - name: Run unit tests
        run: |
          source .venv/bin/activate
          PYTHONPATH=src python -m pytest --color=yes test/*_unit.py