name: Run Tests
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Cache virtual environment
        id: cache-venv
        uses: actions/cache@v4
        with:
          path: .venv  # Cache the virtual environment
          key: ${{ runner.os }}-venv-${{ hashFiles('requirements.txt', 'test/test.requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-            

      - name: Remove broken .venv if pip is missing
        run: test -x .venv/bin/pip || rm -rf .venv

      - name: Create virtual environment
        if: steps.cache-venv.outputs.cache-hit != 'true'  # Only create if cache is missing
        run: python -m venv .venv

      - name: Install dependencies
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test/test.requirements.txt

      - name: Ensure pytest is installed
        run: |
          source .venv/bin/activate
          pip install pytest

      - name: Run unit tests
        timeout-minutes: 2
        run: |
          source .venv/bin/activate
          PYTHONPATH=src:test python -m pytest --color=yes test/*_unit.py
