name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      actions: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Get and cache requirements
        uses: ./.github/actions/cached-requirements

      - name: Install mysql-connector
        run: |
          source .venv/bin/activate
          pip install mysql-connector-python

      - name: Run unit tests
        run: |
          source .venv/bin/activate
          PYTHONPATH=src python -m pytest --color=yes test/*_unit.py