name: Run Tests
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Create virtual environment
        run: python -m venv .venv

      - name: Install dependencies
        run: |
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test/test.requirements.txt

      - name: Run unit tests
        timeout-minutes: 2
        run: |
          source .venv/bin/activate
          PYTHONPATH=src:test python -m pytest --color=yes test/*_unit.py
